# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/
"$schema" = "node_modules/wrangler/config-schema.json"
name = "sanity-bot"
main = "src/index.ts"
compatibility_date = "2025-08-05"

[observability]
enabled = true

[triggers]
# UTC timestamp, correspond to 20:30 UTC+8 every Sunday & Saturday
crons = ["30 12 * * SUN,SAT"]

[vars]
template_id = "AAqzHkj1V1v95"
template_version_name = "1.0.4"
